version: '3'

services:
  web:
    build:
      context: .
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - BITBUCKET_TOKEN=$BITBUCKET_TOKEN
    image: aggregit_web
    command: ["gunicorn", "app:app", "-b", "0.0.0.0:5000", "--reload", "--timeout",  "100000"]
    volumes:
      - .:/home/web/
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
